set(_CATKIN_CURRENT_PACKAGE "actor_pos_plugin")
set(actor_pos_plugin_VERSION "0.0.0")
set(actor_pos_plugin_MAINTAINER "sanshiqi <sanshiqi@todo.todo>")
set(actor_pos_plugin_PACKAGE_FORMAT "2")
set(actor_pos_plugin_BUILD_DEPENDS "gazebo_ros" "message_generation" "roscpp" "rospy" "tf")
set(actor_pos_plugin_BUILD_EXPORT_DEPENDS "gazebo_ros" "roscpp" "rospy" "tf")
set(actor_pos_plugin_BUILDTOOL_DEPENDS "catkin")
set(actor_pos_plugin_BUILDTOOL_EXPORT_DEPENDS )
set(actor_pos_plugin_EXEC_DEPENDS "gazebo_ros" "roscpp" "rospy" "tf")
set(actor_pos_plugin_RUN_DEPENDS "gazebo_ros" "roscpp" "rospy" "tf")
set(actor_pos_plugin_TEST_DEPENDS )
set(actor_pos_plugin_DOC_DEPENDS )
set(actor_pos_plugin_URL_WEBSITE "")
set(actor_pos_plugin_URL_BUGTRACKER "")
set(actor_pos_plugin_URL_REPOSITORY "")
set(actor_pos_plugin_DEPRECATED "")