set(_CATKIN_CURRENT_PACKAGE "actor_collisions")
set(actor_collisions_VERSION "0.0.0")
set(actor_collisions_MAINTAINER "Your Name <your@email.com>")
set(actor_collisions_PACKAGE_FORMAT "2")
set(actor_collisions_BUILD_DEPENDS "gazebo_ros" "roscpp")
set(actor_collisions_BUILD_EXPORT_DEPENDS )
set(actor_collisions_BUILDTOOL_DEPENDS "catkin")
set(actor_collisions_BUILDTOOL_EXPORT_DEPENDS )
set(actor_collisions_EXEC_DEPENDS "gazebo_ros" "roscpp")
set(actor_collisions_RUN_DEPENDS "gazebo_ros" "roscpp")
set(actor_collisions_TEST_DEPENDS )
set(actor_collisions_DOC_DEPENDS )
set(actor_collisions_URL_WEBSITE "")
set(actor_collisions_URL_BUGTRACKER "")
set(actor_collisions_URL_REPOSITORY "")
set(actor_collisions_DEPRECATED "")